__Ziko__.ExtractAll()
__ZikoGl__.ExtractAll()
__Ziko__.__Config__.setDefault({target:document.body})
gl=SceneGl(300,300)
gl.add(cube3(2))
gl.useOrbitControls()
br()
css=SceneCss(700,300)
//css.add(UI3(p("1")))
css.camera.posZ(100)
css.background("#000000")
css.add(UI3(p("Hello World \n from ZikoGl").style({border:"1px solid gold",padding:"10px",color:"gold"})))
//css.useOrbitControls()
